---
fixtures:
  repositories:
    auditd:     "git://github.com/simp/pupmod-simp-auditd"
    compliance: "https://github.com/trevor-vaughan/pupmod-compliance"
    iptables:   "git://github.com/simp/pupmod-simp-iptables"
    mozilla:    "git://github.com/simp/pupmod-simp-mozilla"
    simplib:    "git://github.com/simp/pupmod-simp-simplib"
    stdlib:     "git://github.com/simp/puppetlabs-stdlib"
    xwindows:   "git://github.com/simp/pupmod-simp-xwindows"
  symlinks:
    windowmanager: "#{source_dir}"
