---
fixtures:
  repositories:
    concat:               "https://github.com/simp/puppetlabs-concat"
    inifile:              "https://github.com/simp/puppetlabs-inifile"
    polkit:               "https://github.com/simp/pupmod-simp-polkit"
    simplib:              "https://github.com/simp/pupmod-simp-simplib"
    stdlib:               "https://github.com/simp/puppetlabs-stdlib"
  symlinks:
    gnome: "#{source_dir}"
